name: listdiff
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  more: ^3.10.0
dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
  test: ^1.24.0
