name: listdiff
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  more: ^3.8.0
dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
  test: ^1.21.0
