name: listdiff
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  more: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  test: any