name: listdiff
description: Library for line diffing.

environment:
  sdk: ^3.4.0
dependencies:
  more: ^4.0.0
  web: ^0.5.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
  test: ^1.24.0