name: listdiff
description: Library for line diffing.

environment:
  sdk: ^3.7.0
dependencies:
  more: ^4.3.0
  web: ^1.0.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^5.0.0
  test: ^1.25.0
