name: listdiff
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  more: ^3.3.0
dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
  test: ^1.17.0
