name: listdiff
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  more: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  test: ^1.16.0
